name: Build and release

on:
  push:
    branches:
      - trunk
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - trunk

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup set profile default
      - name: Run cargo check
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup set profile minimal
      - name: Run cargo test
        run: cargo test

  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
      - lint
    strategy:
      fail-fast: false
      matrix:
        include:
          # 64-bit macOS
          - target: x86_64-apple-darwin
            archive: zip
          # 64-bit MinGW (Windows 7+)
          - target: x86_64-pc-windows-gnu
            archive: zip
          # 64-bit Linux
          - target: x86_64-unknown-linux-gnu
            archive: tar.gz

          # ARM64 Linux
          - target: aarch64-unknown-linux-gnu
            archive: tar.gz
          # ARM64 macOS
          - target: aarch64-apple-darwin
            archive: tar.gz
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          MINIFY: "yes"
          TOOLCHAIN_VERSION: stable
