name: Build and release

on:
  push:
    branches:
      - trunk
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - trunk

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup set profile default
      - name: Run cargo check
        run: cargo fmt --all -- --check
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: rustup set profile minimal
      - name: Run cargo test
        run: cargo test

  build-linux:
    name: build ${{ matrix.target }}
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
      - lint
    strategy:
      fail-fast: false
      matrix:
        target:
          # 64-bit MinGW (Windows 7+)
          - x86_64-pc-windows-gnu
          # 64-bit Linux
          - x86_64-unknown-linux-gnu
          # ARM64 Linux
          - aarch64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          rustup set profile minimal
          rustup target add ${{ matrix.target }}
          cargo install cross --git https://github.com/cross-rs/cross

      - name: Compile release
        run: cross build --verbose --release --target ${{ matrix.target }}
      - name: Create archive
        working-directory: target/${{ matrix.target }}/release
        run: |
          tar ca --exclude=jwctl.d -f jwctl-${{ matrix.target }}.tar.gz jwctl*
          mv jwctl-${{ matrix.target }}.tar.gz ../../../
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: jwctl-release
          path: jwctl-*.tar.gz

  build-macos:
    name: build macos ${{ matrix.target }}
    runs-on: macos-latest
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - test
      - lint
    steps:
      - uses: actions/checkout@v3
      - name: Install toolchain
        run: |
          rustup set profile minimal
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin
      - name: Compile x64 release
        run: cargo build --verbose --release --target x86_64-apple-darwin
      - name: Compile ARM release
        run: cargo build --verbose --release --target aarch64-apple-darwin
      - name: Create archive
        run: |
          tar caf jwctl-aarch64-apple-darwin.tar.gz -C target/aarch64-apple-darwin/release jwctl
          tar caf jwctl-x86_64-apple-darwin.tar.gz -C target/x86_64-apple-darwin/release jwctl
      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: jwctl-release
          path: jwctl-*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs:
      - build-linux
      - build-macos
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: jwctl-release
          path: release/
      - name: Publish release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: release/*
